#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    sudo bash $0
    exit
fi

verify_distribution(){
    if [ -f /etc/os-release ]; then
        # freedesktop.org and systemd
        . /etc/os-release
        OS=$NAME
        VER=$VERSION_ID
    elif type lsb_release >/dev/null 2>&1; then
        # linuxbase.org
        OS=$(lsb_release -si)
        VER=$(lsb_release -sr)
    elif [ -f /etc/lsb-release ]; then
        # For some versions of Debian/Ubuntu without lsb_release command
        . /etc/lsb-release
        OS=$DISTRIB_ID
        VER=$DISTRIB_RELEASE
    elif [ -f /etc/debian_version ]; then
        # Older Debian/Ubuntu/etc.
        OS=Debian
        VER=$(cat /etc/debian_version)
    else
        echo "Could not verify distribution or distribution is not supported."
    fi
}

install_ubuntu(){
    app_home="/opt/scripts/yhbp/"
    sudo service yhbp stop
    echo "Removing old files if available..."
    rm /var/log/yhbp.install.log &> /var/log/yhbp.install.log
    rm -r $app_home &> /var/log/yhbp.install.log
    rm /var/log/yhbp.log &> /var/log/yhbp.install.log
    rm /etc/init.d/yhbp &> /var/log/yhbp.install.log
    git clone https://gitlab.zeus-coding.de/arlindne/yhbp.git &> /var/log/yhbp.install.log
    cd yhbp
    mv ubuntu/yhbp /etc/init.d/ 
    chmod +x /etc/init.d/yhbp
    mkdir -p $app_home
    touch "$app_home.yhbp"
    mv ubuntu/yhbp.sh $app_home    
    sudo update-rc.d yhbp defaults &> /var/log/yhbp.install.log
    sudo service yhbp restart &> /var/log/yhbp.install.log
    cd ..
    rm -r yhbp
    rm /var/log/yhbp.install.log
    # shred -u $0 &> /var/log/yhbp.install.log
}

verify_distribution
echo "Installing yhbp..."
if [[ ${OS,,} == "ubuntu" ]]; then    
    install_ubuntu
fi